name = "Antistasi Ultimate Android Extender";
logo = "\x\A3UE\addons\core\Pictures\antistasi_ultimate_logo_sw.paa";
logoOver = "\x\A3UE\addons\core\Pictures\antistasi_ultimate_logo.paa";
logoSmall = "\x\A3UE\addons\core\Pictures\antistasi_ultimate_logo_small.paa";
// picture = "\x\A3UE\addons\core\Pictures\antistasi_ultimate_overview.paa";
author = "Silence";
description = "";
tooltip = "Antistasi Ultimate Android Extender";
tooltipOwned = "Antistasi Ultimate Android Extender";
overview = "<br/><t align='center' size='0.75'> An extender addon for Antistasi Ultimate, adding Android themed sci-fi factions. </t><br/><br/>";
actionName = "GitHub";
action = "https://github.com/SilenceIsFatto/A3UExtender-Androids";
hideName = 0;
hidePicture = 0;
dlcColor[] = {0.1765, 0.6392, 0.6235, 1};
